{% set name = "assimp" %}
{% set version = "5.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/assimp/assimp/archive/v{{ version }}.tar.gz
  sha256: 11310ec1f2ad2cd46b95ba88faca8f7aaa1efe9aa12605c55e3de2b977b3dbfc
  patches:
    - patch.diff  # [linux]
    - fix_cmake_config.diff
    - do_not_export_debug_symbols_gcc.patch

build:
  number: 7
  skip: True  # [s390x]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make  # [unix]
    - patch  # [unix]
    - m2-patch  # [win]
  host:
    - boost-cpp 1.82
    - zlib
  run:
    - boost-cpp
    - zlib

test:
  commands:
    - test -f $PREFIX/include/assimp/anim.h  # [unix]
    - test -f $PREFIX/lib/libassimp${SHLIB_EXT}  # [unix]
    - if exist %LIBRARY_PREFIX%\include\assimp\anim.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\assimp-vc140-mt.lib (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\bin\assimp-vc140-mt.dll (exit 0) else (exit 1)  # [win]

about:
  home: https://assimp.org/
  summary: A library to import and export various 3d-model-formats including scene-post-processing to generate missing render data.
  description: |
    Open Asset Import Library is a library to load various 3d file formats into a shared, in-memory format. 
    It supports more than 40 file formats for import and a growing selection of file formats for export.
  dev_url: https://github.com/assimp/assimp
  doc_url: https://assimp-docs.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
    - jcarpent
