{% set name = "assimp" %}
{% set version = "6.0.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d1822d9a19c9205d6e8bc533bf897174ddb360ce504680f294170cc1d6319751

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make  # [unix]
  host:
    - zlib {{ zlib }}
  run:
    - zlib

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ninja
    - cmake
  files:
    - test
  # The test commands are moved into run_test.bat and run_test.sh

about:
  home: https://assimp.org/
  summary: A library to import and export various 3d-model-formats including scene-post-processing to generate missing render data.
  description: |
    Open Asset Import Library is a library that loads various 3D file formats into a shared, in-memory format.
    It supports more than 40 file formats for import and a growing selection of file formats for export.
  dev_url: https://github.com/assimp/assimp
  doc_url: https://assimp-docs.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
    - jcarpent
