travis:
  secure:
    BINSTAR_TOKEN: SU5B0ljJFf3fu1pZqJqCGz8RT5oD9flVASHEZxj28Iw+bjM3SVATHuWEuR2Ki4+V49Hi3h6NFJAMsjNyRXOODd8E5NgNL67Lkm748gK8o+BLk+VdXZrxesb6WQ/Ji5PQxEW7nK/IJQM/TwNs0I8WwBHHOkrPFr0Rb4UMZRGaeTreQy7sKIfbeLG02XRRVG0zlyGdyvJL+U0I5CbUExdp/IeXpc7l5abg47OmnfPFdJFObvRer/PkTQodeHEKovtsTdrlbKE+rVek7juSkzjvX6xywV+h6cI4g+o04cmmZoJhw9Wcghl0CyDA2o9yN0BLQVgcQ02gS9q4Kf4XTrkL5y68lWJSo90c/X5h52y07H1YBeEAYq0NImJ6gn4XSYnUfVlGCJS9yvM+3lZbDfqx8tCeS0KQ1OVE5Ppw/GEX9EmfyoyuCBP1bVvS79LXUf2FbIFvw9VlOfnfPpLzmt/ia7CqT0uQQraw1So3EI4zRz3SHRwG8d0jLXhoBNF2qI2104D5d6tE0dAjqDedPPebmYzGvs7tWhYGXSAjtI7gJXH2EQAOF7aFhw5UlaH30VgPyNM57Iq9c0sY9JzBuTVIT7THyxeqhPNmocHdpzDtqLh1v+u7Pmj1vrq4RHKiTyGU0rjAwn/EBp5ADxvIuNwIfsNbyHJpfxH3sBxqYNn1e64=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
